name: malsat_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  custom_navigator:
    git:
      url: https://github.com/kjawadDeveloper/Custom-navigator.git
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pixel_perfect: ^1.1.0
  http: ^0.13.1
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/category

  fonts:
    - family:  Custom
      fonts:
        - asset: fonts/Custom.ttf
    - family:  CategoryIcons
      fonts:
        - asset: fonts/category/MyFlutterApp.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
