name: malsat_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  custom_navigator:
    git:
      url: https://github.com/kjawadDeveloper/Custom-navigator.git
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  http: ^0.13.3
  intl: ^0.17.0
  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/category/

  fonts:
    - family:  Custom
      fonts:
        - asset: fonts/Custom.ttf
    - family:  CategoryIcons
      fonts:
        - asset: fonts/category/MyFlutterApp.ttf
    - family:  SocialNetworks
      fonts:
        - asset: fonts/SocialNetworks.ttf
